-- MySQL Script generated by MySQL Workbench
-- Sat 09 Dec 2017 09:29:11 AM CAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AAS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AAS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AAS` DEFAULT CHARACTER SET utf8 ;
USE `AAS` ;

-- -----------------------------------------------------
-- Table `AAS`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AAS`.`courses` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AAS`.`lecturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AAS`.`lecturers` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `uname` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AAS`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AAS`.`departments` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AAS`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AAS`.`students` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `reg_num` VARCHAR(20) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `dep_ID` INT NOT NULL,
  `year` INT NOT NULL,
  `trimester` INT NOT NULL,
  `session` CHAR(1) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `dep_ID_idx` (`dep_ID` ASC),
  CONSTRAINT `dep_ID`
    FOREIGN KEY (`dep_ID`)
    REFERENCES `AAS`.`departments` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AAS`.`timetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AAS`.`timetable` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `course_ID` INT NOT NULL,
  `dep_ID` INT NOT NULL,
  `year` INT NULL,
  `trimester` INT NULL,
  `session` CHAR(1) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `lecturer_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `dep_ID_idx` (`dep_ID` ASC),
  INDEX `lecturer_ID_idx` (`lecturer_ID` ASC),
  INDEX `course_ID_idx` (`course_ID` ASC),
  CONSTRAINT `dep_ID`
    FOREIGN KEY (`dep_ID`)
    REFERENCES `AAS`.`departments` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `lecturer_ID`
    FOREIGN KEY (`lecturer_ID`)
    REFERENCES `AAS`.`lecturers` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `course_ID`
    FOREIGN KEY (`course_ID`)
    REFERENCES `AAS`.`courses` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AAS`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AAS`.`attendance` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `student_ID` INT NOT NULL,
  `reg_num` VARCHAR(45) NOT NULL,
  `dep_ID` INT NOT NULL,
  `course_ID` INT NOT NULL,
  `session` CHAR(1) NULL,
  `lecturer_ID` INT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
  `obs` CHAR(1) NULL,
  PRIMARY KEY (`ID`),
  INDEX `dep_ID_idx` (`dep_ID` ASC),
  INDEX `course_ID_idx` (`course_ID` ASC),
  INDEX `student_ID_idx` (`student_ID` ASC),
  INDEX `lecturer_ID_idx` (`lecturer_ID` ASC),
  CONSTRAINT `dep_ID`
    FOREIGN KEY (`dep_ID`)
    REFERENCES `AAS`.`departments` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `course_ID`
    FOREIGN KEY (`course_ID`)
    REFERENCES `AAS`.`courses` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_ID`
    FOREIGN KEY (`student_ID`)
    REFERENCES `AAS`.`students` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `lecturer_ID`
    FOREIGN KEY (`lecturer_ID`)
    REFERENCES `AAS`.`lecturers` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AAS`.`att_check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AAS`.`att_check` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `lecturer_ID` INT NOT NULL,
  `course_ID` INT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  INDEX `lecturer_ID_idx` (`lecturer_ID` ASC),
  INDEX `course_ID_idx` (`course_ID` ASC),
  CONSTRAINT `lecturer_ID`
    FOREIGN KEY (`lecturer_ID`)
    REFERENCES `AAS`.`lecturers` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `course_ID`
    FOREIGN KEY (`course_ID`)
    REFERENCES `AAS`.`courses` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AAS`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AAS`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AAS`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AAS`.`messages` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `lecturer_ID` INT NOT NULL,
  `student_ID` INT NOT NULL,
  `phone` VARCHAR(45) NULL,
  `message` TEXT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `obs` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `lecturer_ID_idx` (`lecturer_ID` ASC),
  INDEX `student_ID_idx` (`student_ID` ASC),
  CONSTRAINT `lecturer_ID`
    FOREIGN KEY (`lecturer_ID`)
    REFERENCES `AAS`.`lecturers` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_ID`
    FOREIGN KEY (`student_ID`)
    REFERENCES `AAS`.`students` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AAS`.`holidays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AAS`.`holidays` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
